osx_image: xcode10.2
language: objective-c
xcode_workspace: TesserCube.xcworkspace
xcode_scheme: Tessercube
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
cache: cocoapods
before_install:
  - pod install